### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Goodnato**
Q: Would you also like a **Thank you PHP** badge on your GitHub profile?

* Yes

### CODE REVIEW

**Comment by Goodnato** [comment]
Beautiful project, thanks ❤️

**Review by petk — APPROVED** [review]
Thanks @Goodnato and most welcome here :tada: :heart:

**Comment by Goodnato** [comment]
Can i be a part of this organization github. and become a part of them https://github.com/orgs/thank-you-php/people?

**Comment by petk** [comment]
> Can i be a part of this organization github. and become a part of them https://github.com/orgs/thank-you-php/people?

of course! You've just received the invitation and you should be all set up now :)

**Pull request merged**
